// AUTH
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// USER
export const GET_USER_START   = 'GET_USER_START'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL    = 'GET_USER_FAIL'

// DOCTOR
export const GET_DOCTOR_START   = 'GET_DOCTOR_START'
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS'
export const GET_DOCTOR_FAIL    = 'GET_DOCTOR_FAIL'

// GUARDIAN
export const GET_GUARDIAN_START   = 'GET_GUARDIAN_START'
export const GET_GUARDIAN_SUCCESS = 'GET_GUARDIAN_SUCCESS'
export const GET_GUARDIAN_FAIL    = 'GET_GUARDIAN_FAIL'

// INSTITUTION
export const GET_INSTITUTION_START   = 'GET_INSTITUTION_START'
export const GET_INSTITUTION_SUCCESS = 'GET_INSTITUTION_SUCCESS'
export const GET_INSTITUTION_FAIL    = 'GET_INSTITUTION_FAIL'

// LOCATION_SERVICE
export const GET_LOCATION_SERVICE_START   = 'GET_LOCATION_SERVICE_START'
export const GET_LOCATION_SERVICE_SUCCESS = 'GET_LOCATION_SERVICE_SUCCESS'
export const GET_LOCATION_SERVICE_FAIL    = 'GET_LOCATION_SERVICE_FAIL'
